const WORDS_DATA = {
  words: [
    "JESUS", "MARIA", "PEDRO", "PAULO", "LUCAS", "TIAGO", "JUDAS", "JONAS", "SAULO", "DAVID", "ISAAC", "JACOB",
    "NAOMI", "ESTER", "MOISES", "JOSUE", "LAZARO", "PILATO", "BALAM", "SARAI", "ISMAEL", "JETRO", "MIRIA", "CALEB",
    "JESSE", "JOABE", "ABNER", "NABAL", "ASAFE", "SINAI", "BABEL", "EGITO", "SIRIA", "SALEM", "BELEM", "ASSUR",
    "MOABE", "JORDA", "SIDON", "TIROS", "PATMO", "TARSO", "CRETA", "MALTA", "ALTAR", "SANTO", "ANJOS", "SALMO",
    "PODER", "JUSTO", "SABIO", "SERVO", "SALVO", "REINO", "GRACA", "HONRA", "FORTE", "MANSO", "FIRME", "PURO",
    "LIMPO", "PROVA", "PACTO", "VALOR", "VIVER", "UNIDO", "LIVRE", "PEDRA", "PORTA", "MANTO", "LIVRO", "TRIGO",
    "VINHO", "PEIXE", "BARCO", "FIGOS", "MONTE", "TORRE", "PALMA", "COROA", "OLEO", "VELAS", "MIRRA", "MEIGO",
    "DIGNO", "NOBRE", "PLENO", "CASTO", "BISPO", "PADRE", "BENCA", "CREDO", "CULTO", "JEJUM", "REZAR", "ORAR",
    "SACRO", "GRATO", "SALVA", "UNGIR", "SEARA", "PREGA", "CEDRO", "OLIVA", "POMBA", "LEOES", "OASIS", "ROCHA",
    "AREIA", "FRUTO", "VINHA", "CEIFA", "DENSO", "FARDO", "IDEAL", "JEITO", "LEITO", "MAGIA", "NORTE", "OBRA",
    "PASSO", "QUEDA", "RAZAO", "SENSO", "TEXTO", "UNICO", "VASTO", "ELIAS", "OSEAS", "ESDRA", "ABRAO", "CANAA",
    "GOSEN", "MISSA", "VIGIA", "LOUVA", "CRIAI", "CRIOU", "CREIO", "AMIGO", "AMIGA", "CASAS", "CASAL", "OUTRO",
    "OUTRA", "CORES", "CORPO", "TEMPO", "ONTEM", "TARDE", "NOITE", "MANHA", "TERRA", "AGUAS", "FOGOS", "FOLHA",
    "FRUTA", "VENTO", "CHUVA", "NUVEM", "ANTES", "DESTE", "DISSO", "FALAR", "FEITO", "DISSE", "DIZER", "OUVIR",
    "MORTE", "VIVOS", "SORTE", "CLARO", "SUAVE", "RAPID", "LENTO", "FELIZ", "SORRI", "FIRMA", "NIVEL", "MODOS",
    "TOTAL", "PARTE", "COMUM", "ALUNO", "ALUNA", "NOTAS", "LINHA", "PAGIN", "FICHA", "LISTA", "GUIAS", "MAPAS",
    "ROTAS", "RURAL", "LUGAR", "CAMPO", "CAMIN", "PRAIA", "HOTEL", "TRENO", "METRO", "AUTOS", "CARRO", "BUSES",
    "NAVIO", "AVIAO", "PONTE", "CURVA", "RETAS", "ARENA", "AREAS", "AREAL", "FATOR",
  ],
    hints: {
        // Nomes bíblicos
        "JESUS": "Salvador do mundo segundo a fé cristã",
        "MARIA": "Mãe de Jesus",
        "PEDRO": "Pescador que se tornou apóstolo",
        "PAULO": "Apóstolo dos gentios",
        "LUCAS": "Médico que escreveu um dos evangelhos",
        "TIAGO": "Irmão de João, um dos doze apóstolos",
        "JUDAS": "Traiu Jesus por 30 moedas de prata",
        "JONAS": "Profeta engolido por um grande peixe",
        "SAULO": "Nome original do apóstolo Paulo",
        "DAVID": "Rei que derrotou Golias",
        "ISAAC": "Filho de Abraão e Sara",
        "JACOB": "Teve doze filhos que formaram as tribos de Israel",
        "NAOMI": "Sogra de Rute",
        "ESTER": "Rainha que salvou seu povo",
        "JOSUE": "Sucessor de Moisés",
        "LAZARO": "Homem que Jesus ressuscitou",
        "PILATO": "Governador romano que condenou Jesus",
        "BALAM": "Profeta que teve uma jumenta falante",
        "SARAI": "Nome original de Sara",
        "ISMAEL": "Filho de Abraão com Agar",
        "JETRO": "Sogro de Moisés",
        "MIRIA": "Irmã de Moisés",
        "CALEB": "Espião que trouxe bom relatório da terra prometida",
        "JESSE": "Pai do rei Davi",
        "JOABE": "General do exército de Davi",
        "ABNER": "General do exército de Saul",
        "NABAL": "Homem tolo que se opôs a Davi",
        "ASAFE": "Músico e compositor de salmos",
        
        // Lugares bíblicos
        "SINAI": "Monte onde Moisés recebeu os 10 mandamentos",
        "BABEL": "Torre construída para alcançar o céu",
        "EGITO": "Terra dos faraós",
        "SIRIA": "País ao norte de Israel",
        "SALEM": "Cidade da paz, antiga Jerusalém",
        "BELEM": "Cidade onde Jesus nasceu",
        "ASSUR": "Capital da Assíria",
        "MOABE": "Terra dos descendentes de Ló",
        "JORDA": "Rio onde Jesus foi batizado",
        "SIDON": "Antiga cidade fenícia",
        "TIROS": "Cidade costeira importante",
        "PATMO": "Ilha onde João escreveu Apocalipse",
        "TARSO": "Cidade natal de Paulo",
        "CRETA": "Ilha onde Tito ministrou",
        "MALTA": "Ilha onde Paulo naufragou",
        
        // Objetos sagrados
        "ALTAR": "Local de sacrifício e adoração",
        "SANTO": "Separado para Deus",
        "ANJOS": "Mensageiros celestiais",
        "SALMO": "Cântico sagrado",
        "PODER": "Força divina",
        "JUSTO": "Que age conforme a lei de Deus",
        "SABIO": "Que tem o conhecimento de Deus",
        "SERVO": "Aquele que serve a Deus",
        "SALVO": "Liberto do pecado",
        "REINO": "Domínio de Deus",
        "GRACA": "Favor imerecido de Deus",
        "HONRA": "Dignidade e respeito",
        "FORTE": "Cheio de força",
        "MANSO": "Gentil e humilde",
        "FIRME": "Inabalável na fé",
        "LIMPO": "Sem pecado",
        "PROVA": "Teste de fé",
        "PACTO": "Acordo com Deus",
        "VALOR": "Coragem e bravura",
        "VIVER": "Ter vida em abundância",
        "LIVRE": "Sem amarras do pecado",
        "PEDRA": "Símbolo de firmeza",
        "PORTA": "Entrada para o reino",
        "MANTO": "Veste sagrada",
        "LIVRO": "Escritura sagrada",
        "TRIGO": "Grão usado para fazer pão",
        "VINHO": "Bebida da última ceia",
        "PEIXE": "Símbolo dos primeiros cristãos",
        "BARCO": "Meio de transporte dos apóstolos",
        "FIGOS": "Fruta comum na terra prometida",
        "MONTE": "Local de encontro com Deus",
        "TORRE": "Lugar de vigilância",
        "PALMA": "Símbolo de vitória",
        "COROA": "Símbolo de realeza",
        "OLEO": "Usado para ungir",
        "VELAS": "Iluminam o templo",
        "MIRRA": "Especiaria preciosa",

        // Dicas para novas palavras
        "CEIFA": "Época da colheita",
        "DENSO": "Algo espesso ou compacto, como uma nuvem",
        "FARDO": "Um peso ou carga a ser carregada",
        "IDEAL": "Um padrão de perfeição, um objetivo",
        "JEITO": "Maneira ou modo de fazer algo",
        "LEITO": "Onde se dorme ou o fundo de um rio",
        "MAGIA": "Prática de rituais e feitiços",
        "NORTE": "Ponto cardeal, direção a seguir",
        "OBRA": "Trabalho, criação, feito notável",
        "PASSO": "Movimento de um pé ao caminhar",
        "QUEDA": "Ato de cair, declínio",
        "RAZAO": "Faculdade de pensar, motivo",
        "SENSO": "Capacidade de julgar, juízo",
        "TEXTO": "Conjunto de palavras que formam um escrito",
        "UNICO": "Que não tem igual",
        "VASTO": "Muito grande, amplo",

        "ELIAS": "Profeta que enfrentou os profetas de Baal",
        "OSEAS": "Profeta que falou do amor fiel de Deus",
        "ESDRA": "Escriba que liderou o retorno do exílio",
        "ABRAO": "Patriarca chamado para uma grande nação",
        "CANAA": "Terra prometida a Israel",
        "GOSEN": "Região do Egito onde Israel habitou",
        "MISSA": "Celebração litúrgica cristã",
        "VIGIA": "Aquele que vela e guarda",
        "LOUVA": "Ato de exaltar a Deus",
        "CRIOU": "Verbo criar, ligado à obra de Deus",
        "CRIAI": "Imperativo de criar",
        "CREIO": "Profissão de fé (eu creio)",
        "default": "Palavra relacionada à Bíblia ou comum do dia a dia"
        
        // Padrão para palavras sem dica específica

    }
};
